/*

389. Find the Difference


You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.


Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"


Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.


*/

// SOURCE CODE

// BRUTE FORCE
class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        unordered_map<char, int> mpp;
        for (char c : t)
        {
            mpp[c]++;
        }
        for (char c : s)
        {
            mpp[c]--;
        }
        for (auto &c : mpp)
        {
            if (c.second == 1)
                return c.first;
        }

        return '0';
    }
};

// OPTIMAL SOLUTION - XOR

class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        int x = 0, i = 0;
        for (i = 0; i < s.size(); i++)
        {
            x = x ^ (s[i] - 'a');
            x = x ^ (t[i] - 'a');
        }

        x = x ^ (t[i] - 'a');
        char ans = x + 'a';
        return ans;
    }
};